data:
  batch_size: 1
  num_workers: 8
  train_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/images/train"
  train_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/train_annotations.csv"
  
  # val_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/images/val"
  # val_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/val_annotations.csv"

  # val_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/cancer/images/val"
  # val_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/cancer/val_annotations.csv"

  val_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/semi/Kvasir/images_256"
  val_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/semi/Kvasir/val_annotations.csv"

model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  lora_weights: sunseg_output/20250907_1707/best_epoch.pth
  weights_path: weights/groundingdino_swint_ogc.pth
training:
  learning_rate: 0.0001
  num_epochs: 200
  save_dir: test_output
  save_frequency: 5
  use_lora: true
  lora_rank: 32
  visualization_frequency: 5
  warmup_epochs: 5
