data:
  train_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/images/train"
  train_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/train_annotations.csv"
  val_dir: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/images/val"
  val_ann: "/cpfs01/projects-SSD/cfff-906dc71fafda_SSD/gjw_20307130119/sun_seg/48k_256/val_annotations.csv"
  batch_size: 32
  num_workers: 8

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  weights_path: "weights/groundingdino_swint_ogc.pth"

training:
  num_epochs: 200
  learning_rate: 1e-4
  save_dir: "sunseg_output"
  save_frequency: 5
  warmup_epochs: 10
  use_lora: true
  lora_rank: 32
  visualization_frequency: 10

